spring:
  application:
    name: football-api-server

footballapp:
  football-api-baseurl:
        https://jsonmock.hackerrank.com/api/football_matches?year=%s&page=%s
  thread-pool-size:
    25
  jwt-expiry-minutes: 15