version: "3.9"

services:
  football-api-server:
#    command:
#      - "tail"
#      - "-f"
#      - "/dev/null"
    #ensure image has been built and pushed to docker hub
    image: sujaldocker/football-app:b1ecb16d291
    ports:
      - "8080:8080"
    environment:
      FOOTBALL_API_BASEURL: https://jsonmock.hackerrank.com/api/football_matches?year=%s&page=%s
      THREAD_POOL_SIZE: 100
      JWT_EXPIRY_MINUTES: 15
      SECRET_KEY: highly-guarded-secret